# poc-fargate/providers.tf

# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "us-east-2"

  default_tags {
    tags = {
      Environment = "plt"
      Client      = "poc"
      Project     = "poc-fargate"
      Managed     = "terraform"
      Account     = "875004833186"
    }
  }
}

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 6.28.0, < 7.0.0"
    }
  }
}
